#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Cosmos Layer
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Cosmos Layer
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/appl/appl0-cosmos-layer.org
:Created:  2018-02-12T19:22@Prek Leap (11.642600N-104.919210W)
:ID:       6a8fd66a-e10d-4b85-921b-4fe83a8ee8bd
:VER:      571710232.013622797
:GEO:      48P-491193-1287029-15
:BXID:     proj:LOE6-2420
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Introduction

The Cosmos is very difficult to get your head around -- it's
everything that is, in our universe and possibly every other universe
in an infinite multiverse.  But as a practical matter let's restrict
ourselves to our universe and treat our universe as the cosmos.

Matter and energy is interchangable that's the stuff in the universe

But space-time is the fabric -- it is the stuff of the universe

We tend to think of the Big Bang that happened long ago but it's not
true, the big bang is still going on today and will continue to go on
as long as the universe exists, whether it keeps on expanding or
collapses into itself and vanishes into the nothing that it came from.

If we think of the universe as the process that we call the Big Bang,
then couldn't entropy simply be the way we experience how things are
happening in the Big Bang?

This is not some abstract scientific or philosophical question 
because information is the measure of the lack of entropy in a
system.  And information is at the very heart of the concept of
civilization -- if we had no concept of information, there would be no
technological complex societies, communication would have stalled out
at a primitive early verbal stage of development and Man would be only
slightly differentiated from any other species.

We know that information is physical -- that it requires energy to
create and destroy it.

If we can figure out entropy and it's relation to space-time and the
Big Bang then we will....  I'm not sure what we will have, but it will
be important to our long term survival not just as a civiliztion, but
as a species and even the totality of life itself.

There is so much we don't know that we aren't even sure what questions
to ask.  We are still very much as a very primitive level of
understanding what the universe is and how it works.  And as far as
we've come in the past thousands of years, we still really don't know
what we don't know or if we ever can or will.

Since cosmos is the lowest and slowest pace-layer it set's the
baseline rate of change for all of the other layers.  This is a very
useful thing.  It gives the other layers context and scale -- a yard
stick that we can use to measure everything else to understand where
we are relative to the rest of the universe.

So the cosmos layer patterns are not so imporant to directly build a
civilization, but they provide the canvas that the other layers are
built on.  So cosmos layer patterns are somewhat meta in that they are
used to build the helios layer which in turn builds the lithos layer
which builds the bios layer.  So think of the cosmos layer as patterns
that build all of the other layers rather than can be picked out of a
book and applied directly as part of a pattern language for a project.

If you aren't confused right now, then you don't understand...  So the
more we can learn about the cosmos layer the more everything else can
be understood, and the better a civilization we can build.  It's as 
simple and abstract and concrete and elusive as all of that and more.

In the end it's best just accept it as something that is largely
beyond us, which should leave us humbled and awed, but at the same
time not forget that at present we have no idea how much we will be
able to learn so long as we are determined to observe and strive to
understand what we observe.
