#   -*- mode: org; fill-column: 60 -*-

#+TITLE: APPL Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-APPL-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* APPL Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/appl/appl-intro.org
:Created:  2017-12-29T10:19@Prek Leap (11.642600N-104.919210W)
:ID:       6849d064-facf-49c6-b813-55c5765a8027
:VER:      567789629.194913417
:GEO:      48P-491193-1287029-15
:BXID:     proj:VNX0-4036
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Introduction

It's been said that the way we organize information mirrors
the power structure of what is being organized.  If you
reorganize the information it will reorganize the power
structure and vice versa.  So we must take extreme care that
the way we structure a primer for building and maintaining a
civilization from first principles reflects the power
structure of the civilization we are building. It takes
little thought to come to the conclusion this is a
non-trivial problem.

We will employ five overlapping structures, which we will
refer to as =graphs=, =maps=, =threads=, =layers=, and
=heaps=.

#+begin_comment
I've been looking a lot deeper into Big History -- it's
ambitious and comprehensive, with a lot of effort spent on
critical thinking, reading, writing and debating skills.

They see BHP as a origin story from an empirical, rational,
scientific POV that can be used as a framework for all
knowledge.  I agree.  But where BHP is basically a high
school social studies course, I want to take the same
approach to university studies -- as a framework for a
modern take on the Trivium which would provide people with
the equivilent of a Laurea degree that would be a foundation
for lifelong learning.

And then we will broaden the scope to use it as a framework
for building civilization -- with patterns, designs and slow
ai systems SAI that will manage long term processes in the
lower pace layers that keep us on track over time scales
which are too slow for us as individuals to see.

I was thinking about The Young Lady's Illustrated Primer,
which is meant to guide small girls all the way up to the
end of high school age.  After that a whole library opens up
for the girl that includes all of the advanced subject, but
they are  no long within the narrative structure of the
primer.  The student becomes a master who can then write her
own story.

There isn't much mentioned about the more practical things
the primer is teaching, but I am sure that the ideas behind
BHP would fit in well.

The fact that the Primer is structured as an interactive
narrative that takes place in a fairy-tale world is
important.  We need stories and shared myths and legands
that provide us with shared narratives.  Shared mythos is
the cement that holds us together.

This is the thing missing from BHP, and I am not sure how to
provide it.  In the tech community Star Wars and LOTR and
Star Trek and Harry Potter come closest to providing such a
mythological framework,

Harry Potter is the closest to being an over-arching epic
that does what I'm looking for but it's missing some key
elements.

Magic is a something that will mesh well with working with
AIs, incantations and spells are kinds of computer programs
which run when they are cast.

Harry Potter is also something that children can grow up
with.  The books grow up as the children grow up.  The
stories become more complex and subtle as children are able
to understand more and more as they grow up.

We need to imbed a mythos into the interface layer of our
cultural pace layers that interact with technolgy.  A
narrative fictional structure works well for this.

Different cultures could have their own narrative
structures, I wish we could create a single one for everyone
to use.  But there are too many differences in the form of
climate, history, language that need to be localized for
there to be a one-size-fits all.  Harry Potter hinted that
magical world's in different countries are very different.

But it's also important that there are not too many
different narratives.  After all the idea here is that these
are shared narratives is critical.  We don't want this to
splinter into thousands of tiny narratives, like religions
in India.
#+end_comment

*** Graphs**
The primer can best be understood as a =directed graph= that
is a set of =vertices=, or /nodes/ which are connected to
other nodes by =edges=, or /relationships/.  The primer as a
whole forms a =territory=.

Nature is better understood as a /graph/ rather than a
=tree=.  A graph is flexible and resilient which can contain
multiple overlapping tress within it.  The failure of one or
two edges in a tree graph can result in systemic failure.
But a tree which is a subset of a graph remains functional,
giving more time to repair, replace or remap a tree using
other adjacent nodes.  Most monopolies are characterized by
tree-like structures, where power is concentrated in a small
number of nodes which control all other nodes beneath them.
Monopolies are structurally hostile to change, while also
having all of the disadvantages of centralized command and
control structures.

The Westphalian System of Nation States has all but
eradicated other systems during the 20th century.  When
individual states were relatively weak and porous, the
system worked relatively well.  The system has since
ossified into strong states which believe in the illusion of
their inalienable sovereignty.  They are in effect
monopolies which are so resistent to change that they are
unable to cope with external existential change which is
outside their control.

In order to survive, Nation States increasingly depend on
establishing and supporting other commercial and
non-governmental monopolies in order to survive.

*** Maps
A =map= is a representation of a =territory= that is
typically simplified by reducing the =level of detail= (LOD)
that can be observed when looking at a territory as a whole.

This is embodied in the map-territory relationship where
when a map becomes too detailed it becomes a territory in
it's own right.

Maps are very powerful structures.  Our brains can be
thought of as maps of the outside world, that are made up of
a combination of memories and conjecture.  We use these
world maps to navigate the world around us, understand it
and decide what to do next.

The power of maps allows us to comprehend and control
structures which are too large for us to see directly
through our senses.

We can never become conscious omnicient gods because you can
only understand something as a map that is seen from the
outside.  Once that map hits a critical threshold of
complexity it becomes a territory and can not be thought
about becuase you are no longer an outsider looking in, but
a territory in its own right.  A territory can not be
self-conscious because a territory can never see itself as a
whole.  A territory has no means of differentiating itself
from anything else around it because essentual there is
nothing outside of it.  Only subsets of territories can
become self-conscious beings.

   *back this up with TED Talk about scientist having a stroke*

At first glance this might sound like a philosophical
argument that has no practical application but in fact the
reverse is true because it creates a very real threshold for
what can be known.

National surveillance organizations are learning this the
hard way.  The more intelligence you collect, the less you
will be able to learn from it.  The processing power
required to /understand/ data that has been collected
eventually becomes so great that it is no longer
economically practical to do.  But even if you could command
that much computational power, and /everything/ was
processed, the resulting information produced would so large
that it no longer functions as a map.

If you are looking for a needle in a haystack, then you must
find a way of subtracting the large set of hay from the tiny
set of needles which contains only a single item.  The
haystack is so large that is becomes a territory.

The pin can be found by thinking of it as a sorting
problem. There are far better algorithms to do this, but you
can take the haystack and stort everything into two piles, a
pile of straw and a pile of pins.  You will find the pin,
but will have had to throw away most of the information
about the hay.

You could create a map of the haystack, which will make it
possible to understand the structure of the haystack, but
this means that you probably have lost the information of
where a single pin might be within the the stack.

This is similar to the famous double slit experiment in
physics

You can measure something as a set of positions -- a wave,
or as a single position -- a particle, but you can't measure
both at the same time.

In large organizations, those in control need to rely on
maps.  This leads to the illusion that you are looking at a
territory and not a map of a territory.  You have in effect
thrown out all hay but for a handful of things you want to
see in the stack.  For a State that map boils town to
borders, taxes and conscription.  Practically everything
else is lost.  This results in blind spots and a general
misunderstanding of what is really happening until something
becomes large enough to impact borders, taxes and the
ability to conscript soldiers.  When change is slow, large
systems can be controlled in this way, but as the rate of
change increases the handful of parameters that make up your
map will not allow you to understand what is happening.

*** Threads

Think Ariadne's thread....  I love Eco's line that the
thread makes the destination inevitible, the Minotaur is
just thrown in to make things a bit more exciting...

*** Layers

obviously pace layers, but also things like the tcp stack,
different layers with different LODs (such as levels of
difficulty) or POVs.

*** Heaps

heaps (or bags, in RDF) are any set that are not connected
together into a system.

heaps are not bad in themselves -- but they are not living

systems that are made up of strong connections and
relationships have more life, and are.... beautiful.  Broken
systems, are not heaps, but they are failed systems which
tend to be ugly.

** Classes

the primer will be made up of seven broad classes:

  - narratives   : story with a beginning, middle and end
  - patterns     : recognizable set of relationships
  - antipatterns : canary triggers
  - prescripts   : description of procedural information 
  - designs      : specification for contruction of made things
  - terms        : describe or define concepts and ideas
  - authorities  : named instances of persons, places, events

** AntiPatterns

Do we want to include antipatterns?  An antipattern is
canary, something to guard against, so that if the canary
dies, alarms should go off and action taken -- but
antipatterns should not be binary, true or false, right or
wrong.  They are patterns, that are dangerous when they gain
momentum and don't become apparent until they have almost
reached a tipping point.  Every canary must have multiple
triggers that kick in a negative feedback loop that corrects
things, without destroying anything good that is associated
with it.  Canaries don't die unless there is something that
is out of wack that killed the bird.  Just don't use them to
supress change, or growth.  Use them to ensure that change
is happening at a pace that is within cognitive and cultural
limits over larger time frames.  We are bad at recognizing
canaries when they are just starting.  A canary should
trigger at multiple thresholds -- the earliest patterns
should indicate something that should be paid attention to,
and if not corrected should trigger automatic negative
feedback loops whether we've taken action or not.  This is
what Slow AI is for.

In many cases, antipatterns will be considered by some
people in different contexts to be possitive or desireable
patterns.  For this reason each antipattern must have very
strong arguments to support them, even if it is thought that
the reasons are obvious.


** Entity Stack

A hierarchical stack using the FRBR entity model.

  - concept
    - expression
      - manifestation
        - instance
