#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Commerce Layer
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Commerce Layer
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/appl/appl8:commerce-layer.org
:Created:  2018-02-12T18:00@Prek Leap (11.642600N-104.919210W)
:ID:       7ee45e05-f652-428f-9770-f2374a2a1a18
:VER:      571705288.108389532
:GEO:      48P-491193-1287029-15
:BXID:     proj:WVR4-2380
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Introduction

Commerce is interaction, Industry is production.

Commerce needs to be understood as something larger than
from within a capitalist POV.  Even societies which are
organized according to Marxist communist principles have a
commerce layer, as do neolithic bands of hunters-gatherers.
Religions, especially organized religions, have a lot going
on in the commerce layer -- it could be said that religion
is the commerce layer between man and the gods.  A social
contract between a government and it's people is commerce.

If governance is the software, and infrastructure is the
hardware (factories are not commerce they are infrastrucure)
then commerce is a running process.  In fact, commerce is
all about processes and how they are started, run and
completed.  In this respect commerce is a story that two
parties agree apon -- it's all in our heads.

There is a commerce layer in nature but it is physical.
When a lion kills a wildebeast the process of tracking,
stalking, attacking, killing and eating the wildebeast is a
process -- it's linear and it's one way -- at least in
nature you can't unkill something.

Human commerce in an abstract concept that is made possible
by communication between people -- it is the process of
communicating and exchanging things.  Human-stlye exchange
is something that is rare in nature.  There is non-lethal
symbiosis -- a deer eats some fruit, and carries the seeds
many kilometers before it is deposited inside it's feces.
The manure then enriches the soil and helps the seed
germinate and grow.  The tree get's to leverage the deer's
mobility to spread further than if the fruit had simply fell
to the ground and rotted.  In this sense symbiosis is a kind
of physical commerce.  But human communication and exchange
is neither the violent taking of a resource (though we are
all too good at that too) and it is not the same as
symbiosis --- it's far more complex.  In part, this could be
an outgrowth of our natural instinct to nurture our young
and to defend those in our pack -- never forget that we are
pack animals to the very bone and sinew.

Commerce overlaps governance in regulations, laws, contracts
and corporations in fact all of these things have a sort of
dual nature -- a contract is commerce, but it is also a self
imposed regulation or law made between parties.  There are
aspects of thing like marriage that belong to culture,
governance and commerce.  Same goes for a handshake or any
ritual when coming to an agreement.

And let's not forget currency, which is symbolic wealth
backed by force, which at least should be the sole domain of
governance.

If commerce is about interaction and transaction, then
industry is all about production, which is made up of inputs
(materials, mind, memory and energy (muscle)) and outputs
(services and goods).

Commerce creates surpluses (which might be in the form of
olive oil, grains such as corn, wheat and rice, money and
information)

Commerce makes large settlements possible because the larger
the number of people in a group, the more specialization is
required to maintain the survival of the group.  But this
creates inequalities within the group -- different
specialties will be valued more than others.

---

Commerce can be thought of as negotium, which can mean
business or public life which is the opposite of otium,
which is the inner life, retired from business or public
which is used for rest, contemplation and work of the mind.






