#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 09 Fashion Layer
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* 09 Fashion Layer
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/appl/appl9:fashion-layer.org
:Created:  2018-01-06T18:26@Prek Leap (11.642600N-104.919210W)
:ID:       7da07c15-6612-47e8-b41b-3abfd561fe0e
:VER:      568510050.211623075
:GEO:      48P-491193-1287029-15
:BXID:     proj:TWA5-8428
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Introduction
:PROPERTIES:
:ID:       c61139f6-cb3b-4a63-91c8-25c4478582b0
:END:

Fashion patterns are ephemeral, throwing spaghetti at the
wall that lower levels are watching to see what sticks.

So I imagine that many of the Fashion patterns will be about
how to give fashion the freedom to explore without fucking
up lower layers.  This has always been an important function
of any society, which comes in the form of setting limits on
what you can mess with, where you can mess with it and
defining the thresholds to ensure things don't get out of
hand.  This is a delicate balance because it's important to
pay attention to fashion and learn from it.

Fashion is all about risk taking, and risks are, well,
risky.  There is a high rate of failure.

Fashion and popularity are bedfellows and popularity is a
crude blunt instrument, but it has its uses so long as the
popular comes at the expense of more important things,
especially morals and ethics.  Popularity is always
threatening to sweep away things that matter, populism, or
pandering to what is popular is very dangerous because it
preys on our cognitive shortcomings and plays to parts of
our brain that reacts rather than considers.

Fashion is where memes are born.

** The Dark Side of Fashion

The fashion layer is where we experiment, but it's also
where we seek refuge from uncertainty.  The counter culture
was as much escape as revolution. While fundamentalist
religious movements from the American christian and middle
eastern Islamic fundamentalists movements were founded on
fear of change and complexity by embracing certainty and
truth through new retellings of bronze age narratives.
These narratives and the dogmatic world models they
represent are so out of sync with the model of the world
that our senses report to our brains that is leaves people
feeling even more fearful and they they fall deeper and
deeper into a vicious cycle of hate and infighting with each
other as the movements splinter into ever more groups each
offering the promise of the madness of purity that drowns
out the ever shrinking rational voice in their heads
whispering that something has gone terribly wrong.

The newest manifestation of escape is the identity mire,
reinforced by brutal social media peer pressure and enforced
by mob retribution where everyone is so terribly alone and
vulnerable and sick of aspirational consumerism, and
predatory media, and ideological agendas but are too
isolated to do anything but slowly go insane as they loose
touch with reality and the ability to tell what is real,
what is true and what is false.

Fear leads to escape into collective fantasy that only
intensifies the uncertainty so they double down and seek
ever more extreme versions of the same narrative which only
makes things worse.  Humans are terrible at letting go of
beliefs.

Monotheism emerged along side the state.  Polytheism was
always local, tied to the earth that gave birth to the
myriad spirits and gods that connected people to the world
around them.  Monotheism could scale, it was portable and
could map over any local belief system and eventually
smother and overwrite the, leaving only trace etymological
fragments to mark where they had been.

There were some very real advantages to the new system, but
they came at a heavy cost through an ever deepening
estrangement with nature and the physical world, giving the
illusion that man was somehow apart from and above nature.

** Fashion, Commerce, Governance and Culture

Not everything that happens in government takes place in the
goverance layer.  Not everything that happens on Wall Street
or in corporations takes place in the commerce layer.  And
not everything that happens in organized religion takes
place in the culture layer.

A /lot/ happens in the fashion layer and it's difficult
sometimes to understand if a law that was just passed will
have any longer term impact at the goverance layer.

The lower layers are more about long term trends than
specific events.  Fashion is all about the immediate, the
here today and gone tomorrow.

For every "I have a dream" speech by a Martin Luther King,
there are inumerable speechs that are forgotten even as the
echoes of the last words die down in the room.

The ancient Greeks believed in Fate.  But it isn't clear if
everyone has a Fate, only those whose lives the Gods take an
interest in.  Even for those who are Fated to directly
impact the course of history, the vast majority of their
lives are of no more consequence than ours.  Most of us are 
statistical collateral, contributing to things that we may
not live to see play out or understand our part in.

In large part, this is what the Fashion layer is all about.
Lot's of people doing things that in aggregate survive and
percolate down to the lower layers.  We all have our parts
to play, and each part is important, even if we are never
destined to have a Fate.  I see this as a good thing.  In
the Greek stories, the Fates were was seldom if ever kind to
those who lived under their gaze.
