#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Distinct Biospheres
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Distinct Biospheres
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/appl/appl7-biopheres.org
:Created:  2018-01-19T21:52@Prek Leap (11.642600N-104.919210W)
:ID:       562f9712-5808-40df-8ee2-15daa1712a44
:VER:      569645633.198778839
:GEO:      48P-491193-1287029-15
:BXID:     proj:WEL5-4860
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Introduction

What makes this a pattern?  -- because this is the core goldilocks
conditions that make complex life and ecosystems and by extention, us,
possible.

This is the one thing that we must take with us wherever we go, so
long as we are biological creatures.

So we need a definition of what a biosphere is -- in terms of
civilization and as infrastructure -- and what the bare minimum
requirements are needed to consitute a biosphere, and what the
requirements are for a self-contained self-sustaining biosphere 

This creates a baseline for life, human survival and for civilization
not only to survive but to thrive -- what makes an ant-fragile
biosphere?

---

At the time of this writing there are only two biospheres, that of the
earth and the tiny biosphere in a hodgepodge of tin cans that is
called the International Space Station (ISS).

We define a biosphere as a self-contained environment that serves the
function of a habitat that can support multiple forms of life.

We do not include biospheres that are nested within biospheres because
if you crack them open they simply become part of that biosphere.  If
you crack open the ISS, any living thing inside that is not in a space
suit will die.  Space suits, or the inside of a Soyez or space capsule
or other vehicles are a types of transitional biosphere.

Biospheres do not necessarily need to be self-contained or even
self-sustaining to qualify though there is certainly a case to be made
that biospheres should be self-contained and self-sustaining.

A biosphere can contain either an atmosphere or a hydrosphere or a
combination of both.

Biospheres are made up of smaller bioregions, and bioregions made up
of smaller biomes.

Biospheres are systems, with negative and positive regulatory feedback
systems.  ISS is a biosphere because it has a crude regulatory
atmosphere that scrubs CO2 from the air, replenishes oxygen, maintains
a stable temperature and shields occupants from excessive light.

In the case of earth's biosphere it should be remembered that the
biosphere does not provide gravity, the lithosphere in the form of the
mass of the planet provides both gravity and a magnetic field which
helps support life.



 
