#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Infrastructure Layer
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Infrastructure Layer
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/appl/appl7:infrastructure.org
:Created:  2018-01-26T19:16@Prek Leap (11.642600N-104.919210W)
:ID:       d8b7725c-c10b-454a-8fca-034ad32fb190
:VER:      570241061.247609656
:GEO:      48P-491193-1287029-15
:BXID:     proj:OAS1-1083
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Introduction

Infrastructure is near the top of the Pace Layer stack, but it is
pretty slow.

No one wants to invest in infrastructure because repairing a bridge
has to be done, but it's not perceived to be a benefit, so people tend
to put off maintaining infrastructure until it becomes critical.

New infrastructure is an obvious immediate benifit but is expensive
and always complex because in most cases you are displacing people and
property that is being used for other things and there will be a lot
of pushback against proposals.

Steward Brand developed a model for buildings that the Pace Layer
model is based on.  He observed that buildings can be thought of as
being made of of layers that change (replaced, repaired etc) at
different rates.  The furniture in a building might change every year
or so, whereas the building's foundation is rarely repaired or
replaced.

This is a useful way of thinking about any kind of infrastructure.


----

One of my favorite examples of thinking ahead in terms of
infrastructure is found in Thailand and Cambodia.  When national road
systems were planned out as much as fifty years ago or more, land was
allocated for future needs.  So land was set aside for four lane
highways, and utilities were positioned on the far edge of the the
property even though only a two lane road was actually constructured
which may not have be expanded for forty years or more.

The government then was consistent in keeping people from building on
this land, so that when the roads were expanded, starting in the
1990's it was a straight forward process of adding lanes and replacing
the older bridges with larger ones.  The bridges were very old by this
point so they needed replacing anyway.

----

The lower shearing layers should be watched and maintained by Slow AI
systems who save and determine when things need to be replaced or
repaired before they fail.
