#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Lithos Layer
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Lithos Layer
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/appl/appl2:lithos-layer.org
:Created:  2018-01-30T21:24@Prek Leap (11.642600N-104.919210W)
:ID:       9762719f-920b-45f7-9ae7-c15d3c2678b2
:VER:      570594318.692417602
:GEO:      48P-491193-1287029-15
:BXID:     proj:JYW2-4513
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Introduction
:PROPERTIES:
:ID:       35f796f4-47dc-4475-852b-fd494950e63f
:END:

 - [[https://en.wikipedia.org/wiki/Lithosphere][Lithosphere]] | Wikipedia

We will use a rather broad definition of lithos -- to
include any natural infrastructure that supports a
biosphere.  Wholly fabricated infrastructure belongs to the
infrastructure layer.

When talking about planetoid lithospheres we're talking
about not just the crust and mantle (which is technically
the lithosphere) but the whole ball of wax including
magnetic fields created by metalic cores etc. because the
don't really fit in any other layer.  After all this is a
pace layer not limited to the geological term.

---

Plate tectonics is a kind of interface where the biosphere
interacts with the lithosphere to bury carbon which becomes
carbon stores that can be used for fuel (coal, oil and gas).

There is also limestone, which is composed of corals and
other marine life.
---

Does the anthros layer have any impact on the lithos?  I
think that's an important question.

At the moment it would seem conditionally to be yes, but
only if changes can be measured in geological time-scales.

