#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Antifragile Civilization | Meta
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Antifragile Civilization | Meta
:PROPERTIES:
:CUSTOM_ID: appl0:antifragile
:Name:     /home/deerpig/proj/chenla/appl/appl0:antifragile.org
:Created:  2017-12-18T15:06@Prek Leap (11.642600N-104.919210W)
:ID:       e15895b4-0551-4746-99e9-053c09de9ca2
:VER:      566856478.528750804
:GEO:      48P-491193-1287029-15
:BXID:     proj:JHG8-8846
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Introduction

Civilization has always been little more than a thin veneer, a luxury
that can only be indulged when there is a surplus that allows a few
individuals to work on things that are not necessary for immediate
survival.

Nassim Nicholas Taleb coined the phrase /antifragile/ which he defines 
as:

#+begin_quote
Some things benefit from shocks; they thrive and grow when exposed to
volatility, randomness, disorder, and stressors and love adventure,
risk, and uncertainty. Yet, in spite of the ubiquity of the
phenomenon, there is no word for the exact opposite of fragile. Let us
call it antifragile. Antifragility is beyond resilience or
robustness. The resilient resists shocks and stays the same; the
antifragile gets better.
#+end_quote

Life is quite delicate in the instance, but astonishingly tenacious
and resilient in the aggregate.  Despite having gone through 5 major
extinction events that in some cases wiped out over 90% of the species
some of which lingered on for hundreds of thousands of years before
going extinct and others blown out like a candle.  And yet, each time
life roared back to reclaim the planet in ever more complex and
varied forms.



  - adaptation
  - dispersal
  - duplication
  - propagation
  - cooperation


** Adapt
 - adapt to thrive or at least survive in as wide a range of
   environments as possible -- we've been doing this since we left the
   Savannah xxx years ago
 - all about iteration to overcome and transcend our cognitive and
   biological limitations
 - iteration is a non-linear process -- there are dead ends and more
   failures than success.  the only way to succeed is through
   perseverance and relentless trial and error that is always a
   borders on being a sysiphean pursuit for the individual, but in
   aggregate is a powerful strategy
** Disperse 
 - we must expand because no one place will be arond forever, so we
   need to be in as many places as possible to maximize chances of
   survival.
 - stagnation is the first step towards death, it's giving in to
   entropy, the opposite of the process of life
** Duplicate
 - the most antifragile mechanism we know of is life itself, which is
   governed by DNA.  DNA does only two things, duplicate and
   propagate, everything else is a side effect that increases DNA's
   ability to duplicate and propagate
** Propagate
 - dispersal and propagration are an instance of the Janus Pattern,
   disperse and expand wholes, and propagate between the parts --
   traverse a graph, it's a network process.  
** Cooperate
 - which is all about wholes who understand that they are also a part
   of something larger
