#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Freedom of Speech
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Freedom of Speech
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/appl/appl5:speech.org
:Created:  2018-02-09T17:19@Prek Leap (11.642600N-104.919210W)
:ID:       d2474d94-ec55-435e-a28a-c06637270a26
:VER:      571443660.138035796
:GEO:      48P-491193-1287029-15
:BXID:     proj:HAO8-2140
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

bibliography:../hoard/bib.bib

** Introduction

#+begin_quote
"If liberty means anything at all, it means the right to tell people
what they do not want to hear”

— From George Orwell's proposed preface to Animal Farm (1945).
  cite:jennings:2017orwell
#+end_quote

#+begin_quote
Fuck that right! I want the right to talk
I want the right to speak, I want the right to walk
Where I wanna, yell and I'm gonna 
....

You'll censor what we see, we read, we hear, we learn
The books will burn
You better think it out
We should be able to say anything, our lungs were meant to shout
Say what we feel, yell out what's real
Even though it may not bring mass appeal
Your opinion is yours, my opinion is mine
If you don't like what I'm sayin'? Fine
But don't close it, always keep an open mind
A man who fails to listen is blind

-- "Freedom of Speech" Body Count, Ice-T
#+end_quote



What you can say is directly proportionate to the size of your
audience. The larger the audience, the less you can say without offending
someone.

Freedom of speech, as an inalienable right, is about inverting that
truth to protect the minority opinion, the offending, the patently
ubsurd the blatantly offensive.  So this works as a negative feedback
loop, as a check and balance, so that when the majority is wrong, the
minority has the power to correct it, and when the minorty is wrong,
the majority can be aware of it and guard against any harm that can
come of it.

No one has a monopoly on truth, facts or falsehoods. To limit or
silence speech and expression because it does not adhere to the
majority creates positive feedback loops that are at best
self-defeating and at worst are disasterous, if not existential
threats to a society.

But freedom of speech means nothing if people don't have just as
strong protection from those who wish to limit access to that speech.

to limit speech and expression is to censor -- which is the attempt to
control what information people have access too

freedom of speech and freedom of access to speech can not be
separated -- this goes to the heart of transparency which is the
foundation on which accountability is build.  The less transparency,
the less accountability.

time and time again, every society that censors ends up shooting
themselves in the foot.  Their argument is that it is better for them
to manage the filters rather than the members of their societies.  The
problem is that the higher you put filters in a heirarchy, the more
information you loose, you are more often than not throwing out the
baby with the bathwater.

give people the cognitive tools to fashion their own filters, if a
society has nothing to hide, then they have nothing to fear in
protecting the freedom to speak and the freedom to listen.

keeping people in the dark about what is happening and what has been
said must be balanced with ensuring that people have the ability to
make rational informed judgements one what is real or not, what is
true and what is false, what is valuable and what is junk.

keeping people stupid /and/ cutting them off from the world is both
short sighted and self-defeating.

Speech is a superpower worthy of any DC or Marvel Comic superhero.
And unless one has lived under a rock for the past thirty years the
following quotes will likely sound familiar:

#+begin_quote
"Ils doivent envisager qu’une grande responsabilité est la suite
inséparable d’un grand pouvoir."

"They must consider that great responsibility follows inseparably
from great power."

— 1793 French National Convention
#+end_quote

#+begin_quote
The possession of great powers and capacity for good implies equally
great responsibilities in their employment. Where so much has been
given much is required.

— Henry Hayes, quoted in a report by the Trustees of the Public
Library of Boston (1879)
#+end_quote

#+begin_quote
With great power comes great responsibility.

— Uncle Ben, advice to Peter Parker
#+end_quote

Rights are not absolute and must be balanced by obligations to use
those rights responsibily.  You can not have one without the other.

Use of such rights to spread falshoods, that are meant to mislead,
coerce or subjegate must be allowed, but they also must be
counteracted and corrected by rational discourse corroborated by
evidence and that is either exculpatory or conclusively illuminates
the lies and dissembling that ultimately seeks to take those rights
away and destroy us.



free speech is not about truth or falsehoods -- both majorities and
minorities at times lie through their teeth and others are exemplars
or resounding eternal truths.  And it's never quite certain in the
moment which it might be.  Something that sounds perfectly reasonable,
honest and obvious today may well be reguarded as bigoted, shallow
minded hogwash a few decades hence.  In this, as in all things,
context is everything.

Let the slower pace-layers rock away[1] the detritus discarding the
hurried ephemeral, to preserve what's of value in larger and longer
contexts.




** References

contributors, W., /Freedom of speech --- wikipedia, the free
encyclopedia/ (2018).
url: [[https://en.wikipedia.org/wiki/Freedom_of_speech][Freedom of speech]] | Wikipedia
cite:wiki:2017freedom-speech

van Mill, D., Freedom of speech, In E. N. Zalta (Eds.), The Stanford
Encyclopedia of Philosophy (pp. ) (2017). : Metaphysics Research Lab,
Stanford University.
url: [[https://plato.stanford.edu/entries/freedom-speech/][Freedom of Speech]] | Stanford Encyclopedia of Philosophy
cite:sep:2017freedom-speech

Jennings, M., /Orwell Statue Unveiled/ (2017).
cite:jennings:2017orwell

How does this relate to 




Footnotes: 

[1] /Yuri-ita/ (揺り板), Japanese for "rocking plate", used
for panning gold with a rocking motion.

