#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 09 Fashion Layer
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* 09 Fashion Layer
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/appl/appl9:fashion-layer.org
:Created:  2018-01-06T18:26@Prek Leap (11.642600N-104.919210W)
:ID:       7da07c15-6612-47e8-b41b-3abfd561fe0e
:VER:      568510050.211623075
:GEO:      48P-491193-1287029-15
:BXID:     proj:TWA5-8428
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Introduction

   Fashion patterns are ephemeral, throwing spaghetti at the
   wall that lower levels are watching to see what sticks.

   So I imagine that many of the Fashion patterns will be
   about how to give fashion the freedom to explore without
   fucking up lower layers.  This has always been an
   important function of any society, which comes in the
   form of setting limits on what you can mess with, where
   you can mess with it and defining the thresholds to
   ensure things don't get out of hand.  This is a delicate
   balance because it's important to pay attention to
   fashion and learn from it.

   Fashion is all about risk taking, and risks are, well,
   risky.  There is a high rate of failure.

   Fashion and popularity are bedfellows and popularity is a
   crude blunt instrument, but it has its uses so long as
   the popular comes at the expense of more important
   things, especially morals and ethics.  Popularity is
   always threatening to sweep away things that matter,
   populism, or pandering to what is popular is very
   dangerous because it preys on our cognitive shortcomings
   and plays to parts of our brain that reacts rather than
   considers.

   Fashion is where memes are born.
