#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Warp & Woof Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Warp & Woof Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/appl/ww-intro.org
:Created:  2018-02-15T20:19@Prek Leap (11.642600N-104.919210W)
:ID:       f8ae9d01-083a-4598-84e7-249d560fca6c
:VER:      571972838.678903093
:GEO:      48P-491193-1287029-15
:BXID:     proj:OKM3-3142
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Introduction

W&W will be to APPL that /A Timeless Way of Building/ 
(TWB) cite:alexander:1979timeless is to APL. cite:alexander:1977pattern


TWB starts with this:

#+begin_quote
/The Timeless Way of Building/ is the first in a series of
books which describe an entirely new attitude to
architecture and planning.  The books are intended to
provide a complete working alternative to our present ideas
about architecture, building, and planning—an alternative
which will, we hope, gradually replace current ideas and
practices.

— A Timeless Way of Building
  cite:alexander:1979timeless
#+end_quote

Replace architecture and building with civilization and it's
not a bad description of W&W and APPL.

TWB was published two years after APL, which answers the
chicken and egg question, but it also makes sense.  TWB
couldn't have been written until after they had all but
completed APL.

TWB is divided into three Parts: The Quality, The Gate, and
The Way.

   - /Quality/ is QWAN.
   - /The Gate/ is the Patterns.
   - /The Way/ is how to get QWAN using the patterns.

The organization of the book also is design to work at
multiple LODs, like /The Plan of St. Gall/ with an outline
of the entire work, and then detailed TOCs at the beginning
of each volume.



TWB is almost mystical -- it does not come across as a
practical text on how to build according to his philosophy
and methodology.  It's almost a manifesto.  This was on
purpose, but as some reviews have noted, it could be one
reason that it hasn't been treated as seriously as it
should.  It's too outside of the mainstream, too easy to
dismiss and doesn't provide a bridge for architects and
builders to cross from their world into his.

The Oregon Experiment (which I still haven't seen) seems to
be where he shows a concrete example of how to plan, design,
and build.

So what about W&W?  We don't need to build the same bridges
that Alexandar should have, but at the same time we need to
bridge the gulf of how civilization is today, how the
present attempts at change are useless and all but
worthless.  So I suppose we do need bridges.  But is W&W to
be a bridge or manifesto?

I don't want to be too mystical, but I also don't want to be
too concrete which is why I'm so attracted to the Plan of St
Gall (PSG).  St Gall was never built -- so the designs based
on the plan are -- as the title says -- paradigmatic. PSG
delves deep providing historical, social, economic and
archaeological context and evidence.

So I suppose that W&W needs to blaze a path between the two
-- so that it's part Timeless Way and Part Plan of Arc Nong
Pao.

In fact that's about right -- first volume should be closer
to TWB and the following volumes should provide three Plans
-- two on earth and one on mars.

In that respect I suppose we can borrow many things from
Mollison's Designer's Manual -- which is, in many respects,
a path between TWB and PSG.

The whole pace-layer model will take a bit to lay out -- and
we will have to make a case for why we are on the wrong
path, and how we have no choice but to start from first
principles.

** Warp & Woof

The primer for the primer -- a kind of process philosophy
where past is part of the present -- and the future does no
exist you can't go into the future or back to the past
because time is not linear -- we are living in the Big Bang,
we are part of the Big Bang, it didn't create the universe,
it's still going on, it IS the universe.

*** Part One -- name ?????

  - information
  - process
  - part-whole
  - pace-layers
  - systems & distributed systems
  - models & graphs
  - map-territory
  - quality
  - craftsmanship

*** The Plan of Arc Indradevi

A bioregion in n.e. cambodia.  Rather than my original
concept of doing the plan for the Arc itself like PSG, we do
a plan for an entire bioregion and ecosystem for of 2
million people all living and working as part of a global
distributed micro-value-chain.

The Arc will be just one part of the larger plan -- that
will include infrastructure, agriculture, production,
economic, education, governance and culture.

I suppose the plan would be a master plan, and we would
create three different 100 year scenarios of how that plan
might be realized depending on different climate change,
political, and economic scenarios globally and regionally.

My original idea was to do three scenario histories over a
100 year period.  The scenarios would show how generative
designs would create very different things given different
circumstances.

Without this it would be easy to think that this was a
traditional top-down static plan.  We need to show that
generative designs are natural -- for some reason they scare
people, but most of that is because generative plans are
things that happen in the moment, they are processes rather
than plans.  Plans are linear, with a beginning middle and
end -- processes can be linear -- but they can also be
open-ended and they certainly are not deterministic it's not
always clear where a process will lead.  In reality we don't
know where plans lead either -- but in the case of building
physical infrastructure the goal is usually to know what you
are building and ensure it get's built according to plan.
In the case of something like a suspension bridge this is a
good thing.  But not the vast majority of constructions.
The great european cathedrals were not built in the same way
as modern buildings they were generative processes that
took, in some cases, centuries to complete.  There's no
little irony that ESR's famous essay used the catherdral as
the symbol of top down planning, design and construction.

Adaptive processes are better in the long term, but static
processes are percieved to be better in the short term (even
though this is not true) and the modern system from the
ground up is designed to work that way.

This is not to say that generative is all chips and gravy.
Generative is as hard as distributed -- biological evolution
is a blind generative process and is mind blowingly
inefficient.  But when generative works, the payoff is all
of Life in all of its diversity, complexity and beauty.  We
are coded to work this way, even if that coding is working
very deep in the bios pace-layer.  And the thing is,
deterministic processes are almost always bad and if they
aren't, it's little more than chance.  Okay, I take that
back, deterministic processes work at individual human
timescales.  We can get up in the morning, eat breakfast and
go to work.  That's a deterministic process.  We make a plan
and follow it for day to day life.  We can do that and often
do it very well.  But we then try to apply the same approach
to processes in pace-layers that are beyond individuals, and
even beyond collective human pace-layers.  That's where is
all falls apart.

Business plans are a good example.  Business plans are
complete bullshit if they are for longer than a few months.
Five or ten year business plans are meaningless fantasy in
world whose ROC in fashion and commerce pace-layers is as
fast as it is today.  But we persist in thinking that they
are useful and waste enormous amounts of time writing them
and as soon as something changes, they are forgotten in a
drawer.



*** The Plan of Barsoom Dor

Basically the same thing as Indradevi, but how the same
thing might be achieved on Mars.

A man-made underground river (not a tunnel, but a river with
banks and air above) that runs from south towards the
equator that is fed by ice from antarctic to domes in warmer
climes.  The river feed domes that create atmosphere, and
hydrosphere that make up a distributed biosphere.

*** Dubai Martian City

I'd like to approach the Dubai Mars City project with the
proposal to do three scenarios for them as well -- one will
be our Barsoom Dor scenarios but in addition two others that
explore what a traditional top down design and construction
process might look like and how they would compare to our
generative approach.

This would be done by holding scenario conclaves where we
invite different traditional architects, engineers and
builders and work out the long term consequences of top down
approaches.

To keep participants honest, all scenarios will follow
examples from history of what has happened to planned urban
areas in the past.  We ask them first to come up with a
design and 20 year master plan in brief and then we see how
the plan will adapt over time to things that they didn't
plan for.

But how to do that?  I suppose we have two teams the design
teams, the governance teams and then the historical teams
who would through events at them which came from historical
examples.

One of the scenarios is that after 50 years, Mars is cut off
from Earth for the next 50 years.  This might mean being
physically cut from all contact, or or economically cut off
when funding dries up for support.

We will also throw at them things that will basically force
them to abandon a lot of their initial assumptions after the
settlement is essentially built.  Can they adapt, and in
order to adapt how will it impact their original designs?

** APPL

structures used by the primer

It took me a long time to really grok patterns.  The first
time I saw the book I was hooked instantly.  But how you got
from patterns to actual buildings wasn't so clear.  Even
today, after reading /The Nature of Order/
cite:alexander:2004phenomenon it still wasn't clear.  I
understood what he was proposing, but implementation is
still too fuzzy -- it's almost as if the gulf is too great
between the past and present -- we are so estranged and
broken that building things from a deep sense of
connectedness to the world is an alien concept.  I don't
agree that people still have an innate ability to do this.
This faculty has been so degraded that we don't even know
what we've lost any longer.

Alexander has come up with a methodology that provides a
crude method that's sort of like trying to teach deaf people
to create not just music but /beautiful/ music that they can
not understand or experience.

We need to teach people how to be connected to the world and
give them the cognitive tools to see and appreciate beauty,
then Alexander's approach will follow naturally.

This goes to the core of the problem of quality and
craftsmanship.  And in both cases I don't think we make any
progress until we can at the cultural layer, to reinvent
both quality and craftsmanship.  This is a
multi-generational undertaking and my gut feeling is that we
first need to figure out how to stop crushing children's
natural ability to see and understand beauty.  And I have a
hunch that this can't be done unless we also stop crushing
things like curiosity, or training people to think that
uniformity is the synonymous with quality -- that's an
industrial revolution thing.  

And post-industrial revolution civilization is just getting
worse.  We now have a significant percentage of a generation
who don't experience anything directly -- they are too busy
pointing a camera at things instead of experiencing it and
contemplating on what they are seeing.  Instead they
experience things as a side effect of their peer group in
social media.  That's bad enough, but we then are going
further and feel the need to include ourselves in most and
sometimes nearly all of those photos.  Selfies put ourselves
at the center of everything we experience.  We don't watch a
beautiful sunset, we take a picture of ourselves in front of
a beautiful sunset and by the time you've sent the picture
to social media the sun is down.  We need to understand that
we are part of the world, at the center of that world and
this is something that is being lost.  There are any number
of people who take great umbridge to this argument and say
that taking pictures is how they experience things.  That
doesn't hold up, the act of recording requires that most of
your attention is spent in the mechanics of making that
recording.  Saying that you can multitask and enjoy the sun
set as fully through a view finder as you fiddle with the
settings and frame and take the shot is not the same as
quietly sitting and watching a sun set.  Adding insult to
injury by putting yourself into that shot is pure
narcissism.  It is not a bad thing to take pictures of a
sunset, but this should be the exception rather than the
rule.  If you haven't spent many many sunsets watching them
and trying to understand what you are seeing and how that
relates to you and your place in the world then you don't
have the experience to know how to capture all of that in a
photograph.  This is the difference between art and whatever
it is people are doing with selfie sticks.

When we produce millions of exact copies of things be they
tea pots or copies of a sound recording we have stripped
things of their uniqueness and life imperfections are the
only way we can know when we see something that is perfect.
When everything is the same, there is no good or bad,
nothing is better than anything else which strips things of
their beauty, if nothing is ugly, then nothing is beautiful.
Beauty only exists as part of a spectrum with things that
are ugly at the opposite end.

We have to discard a lot of industrial revolution baggage to
do this and we will never see it, nor out children.  But
perhaps our grandchildren and great grandchilren, if we work
hard enough at it and make it a priority.

But this still doesn't answer my original question of how to
use patterns -- I don't see them as a crutch, as see them as
an important means of embodying an aspect of knowledge that
until now hasn't been recorded in any meaningful way.

Patterns record fuzzy things that we use terms like
traditional, or custom or vernacular that boils down to
being collective, often informal knowledge -- it works
because it has evolved over many generations and tempered
over time through constant tweaking and experimentation.
It's often difficult, and even impossible to boil such
knowledge down into exact specifications or designs.
Patterns are able to capture that and as such are very
powerful, though more than a little nebulous.  Patterns are
not machine understandable because they are all within a
continuum of possible manifestations.  This is why it's so
difficult to use traditional building and financing methods
to do such construction because it is a process that doesn't
lead to a specific pre-defined conclusion.  The process
determines the finished product, not the desgin.  This is
what happened to the Web -- the original Web wasn't supposed
to look the same everywhere -- web pages were supposed to be
rendered differently according to the different types of
software and hardware that was being used.  Today's web
which is designed to work on multiple display sizes is not
what I'm talking about.  Web pages were not meant to be
'designed' they were meant to be interpreted.  Modern man
can't handle that kind of plasticity and uncertainty -- we
are too indoctrinated with the industrial concept that
everything has to be exactly the same to be of high
quality.  There can be no ambiguity, no influence from
outside -- everything must be static cookie cutter identical
copies where the designer has the power of controlling
everything for good or bad.

This also means that we've lost the ability to adapt the
world around us to the specific circumstances and needs that
they are put to use.  Emacs is completely the opposite from
this -- no two .emacs are the same, and after a while, the
customizations that go into your config may well make it
unusable for other people to be able to understand or use.
To someone like Steve Jobs this is nothing short of
horrifying.  He wants to cramp /his/ vision and /his/ design
down your throat and he doesn't give a shit if this works or
not.  Apple products require you to conform in ways that
Microsoft was never clever enough to pull off.  But
microsoft achieved the same thing from a completely
different direction.  Microsoft products are designed for
large corporate environments that require general purpose
tools that are identical.  Microsoft is the electronic
embodiment of industrial information processing.  The tools
don't need to be great, they only need to be good enough,
because the workers and the work done doesn't need to be
great it only needs to be good enough.  Excellence,
ingenuity and imagination doesn't scale and must be
eradicated where ever it is encountered.  That is why
Microsoft was so successful, Gates understood that in his
bones.  Apple then became a sort of fake alternative to
Microsoft.  Apple was supposed to be about individuality and
unconformity and thinking outside of the box, but that was
all window dressing.  It had the effect of catching all of
the people who did have a spark of imagination and crushed
it by reducing it to a lifestyle choice.  So you had the
choice of Microsoft, or Apple's way or the highway.  In the
end both Microsoft and Apple were doing the same thing.

Emacs out-of-the-box isn't emacs.  Emacs only become emacs
after it has rewired your brain and you have rewired emacs.

That is the potential that the web originally had and was
lost in the browser wars.


** Primer

The origin story is the first part of the primer,[fn:1]
followed by the theses (declarations), then education (triv,
quad, laurea etc), then the shops and guilds, then the
value-chain, then bioregions, and finally production.

Man started out just as any other animal on the savannah,
but development of tools, then speech and finally writing
resulted in an estrangement that in our minds that estranged
us from the world and who we were that seemed to have
started with Aristotle and all of those god damned lists and
categories.  It wasn't until the Copernican Revolution which
showed that there was nothing special about where we were in
the universe that we began the slow process of decentering.
The Darwinian Revolution was the second decentering which
taught us that we are just one more creature in a vast
fabric of life and that all of the rules apply to all of us,
we are no exception. I believe that we are at the brink of a
third which will teach us that our minds and our
intelligence is nothing special either.  We've fallen a long
way and we are still falling.  And as anyone who has jumped
out of an airplane could tell you, the fall is nothing to be
afraid of, it's when the ground breaks your fall that you
have to worry about. Intelligence is all around us, we are
simply too caught up in ourselves to notice.  I hope that
when Man does hit bottom that it will leave us humbled and
capable of living within the limits of the ecosystems that
we are part of.  That doesn't mean we will stop hacking them
and shaping them for our own purposes, but it will have to
be with an understanding that we either find a way of living
within the carrying capacity of where we live, or we die.
You can not increase carrying capacity by using up or
abusing resources faster than they can be replaced.  If you
can hack nature to increase sustainible carrying capacity
great -- but that is not what Man is doing now.


  - origin
  - theses
  - education
  - shops & guilds
  - value-chain
  - 
  - bioregions/ecosystems
  - production & surpluses
    - slavery/mass labour -> machinery -> cognitive machines

*** Slavery and Civilization

Two sides to slavery; surplus mind and muscle, you need both to create
a surplus that leads to surpluses that free a proportion of the
population to pursue intellectual pursuits that result in advancements
in technology, sciences and the arts.

This follows toffler -- force -> wealth -> knowledge

  - domesticated animals had the muscle but not the mind so you still
    needed slaves who were compelled through physical force to direct
    the beasts.

  - machines had the muscle but not the mind so you needed captive
    labour in the form of factory workers who were economically
    compelled to work to direct the machines.  This system is more
    flexible and scalable than slavery.

  - when you use machine cognition to direct the machines you get
    robots which does not require compelled human labor.  Ths system
    is more flexible and scalable than mass indusitural human labor.

So when you hear claims that it was machines that were responsible for
ending slavery they are both right and wrong.  The nature of slavery
simply changed from a model based on physical force, to a model based
on symbolic wealth.  The work force might have the illusion of being
free but for all practical purposes it was still slavery.  This then
frames the other claim that it was the development of moral and
ethical motivations that ended slavery.  Those moral arguements were
used to change the nature of slavery, not to end it.  And in so doing
was able to scale slavery to proportions that couldn't have been
dreamed of in the wildest dreams of the most barbaric banna
plantation in central America or Cotton farm in the old south.

However, even before 1800 it's difficult to know how many slaves there
were because not all slaves were called slaves.  Serf's, indentured
labor etc. are all forms of the same shade.  This is also true in the
modern industrial era where incarceration in many places is little
more than another form of legal slavery.  Conscription has also taken
forms that are little different from slavery as well.


** Hoard

After the primer is the Hoard -- the library of descriptive
and prescriptive knowledge.  This will be a map but a very
detailed map whose territory is the archive.

This will be the knowledge that is assembled to build a
civilization from first principles -- this will include
designs, standards, recipes, facts, proceedures, best
practices.

The idea is that you will pick out your patterns and create
your pattern language which is at the core of a master
generative plan -- then you use the knowledge from the Hoard
to build it.

A pattern might be for outdoor windows, and what they must
incorporate to work.  The Hoard will provide the information
for obtaining or creating the building material, wooden,
plastic or metal frame, plate glass, glazing, screws,
caulking and all of the tools needed to build it and then
more general proscriptive steps that make up the art of
glass making, and window framing.

The Archive will be all of the primary documents that the
Hoard is built on.

----

But don't forget that the Hoard has two parts -- map and
territory, so the graph database that weaves it together is
just as important as the items in it.

** Archive

After that is the Archive of all recorded memory and
experience.

Arcs are designed to collect, organize and filter material
over very long time frames.  At set intervals, material in
collections is evaluated and filtered.  This could be
something like every 1, 10, 100 and 1,000 years.

Arcs can be either public or dark -- dark arcs are not
directly accessible and will only respond to requests for
things that have been lost.  Dark arcs will also monitor
public arcs to see what is missing and make that material
available to be found and added.

Dark arcs will be part of the slow internet -- running at
negative bandwidth speeds -- -1G, -2G, -3G etc speeds, as
slow as -5G.

After a massive loss of recorded knowledge after a disaster,
war or other temporary sanity, dark arcs will determine when
people are ready to have that lost knowledge restored.

* Footnotes

[fn:1] What about language?  Origins lays out our history which is
tells what our metaphysics and physics.  The nuts and bolts of laguage
will be in the Triv.  but I'm talking about something deeper, more
structural -- language both spoken, written and executable -- a
language of the long now that will change far slower than language at
the upper pace layers -- it will change, but over centuries and
milennia not years and decades.  It should be something that is stable
for long periods of time.  Different pace-layers will have different
versions of it, the fashion layer tries out new ideas which are
filtered and refined until they change the lowest layers.


