#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Warp & Woof Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Warp & Woof Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/appl/ww-intro.org
:Created:  2018-02-15T20:19@Prek Leap (11.642600N-104.919210W)
:ID:       f8ae9d01-083a-4598-84e7-249d560fca6c
:VER:      571972838.678903093
:GEO:      48P-491193-1287029-15
:BXID:     proj:OKM3-3142
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Introduction

W&W will be to APPL that /A Timeless Way of Building/ 
(TWB) cite:alexander:1979timeless is to APL. cite:alexander:1977pattern


TWB starts with this:

#+begin_quote
/The Timeless Way of Building/ is the first in a series of books which
describe an entirely new attitude to architecture and planning.  The
books are intended to provide a complete working alternative to our
present ideas about architecture, building, and planning—an
alternative which will, we hope, gradually replace current ideas and
practices.

— A Timeless Way of Building
  cite:alexander:1979timeless
#+end_quote

Replace architecture and building with civilization and it's not a bad
description of W&W and APPL.

TWB was published two years after APL, which answers the chicken and
egg question, but it also makes sense.  TWB couldn't have been written
until after they had all but completed APL.

TWB is divided into three Parts: The Quality, The Gate, and The Way.

The organization of the book also is design to work at multiple LODs,
like /The Plan of St. Gall/ with an outline of the entire work, and
then detailed TOCs at the beginning of each volume.



