#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Warp & Woof Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Warp & Woof Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/appl/ww-intro.org
:Created:  2018-02-15T20:19@Prek Leap (11.642600N-104.919210W)
:ID:       f8ae9d01-083a-4598-84e7-249d560fca6c
:VER:      571972838.678903093
:GEO:      48P-491193-1287029-15
:BXID:     proj:OKM3-3142
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Introduction

W&W will be to APPL that /A Timeless Way of Building/ 
(TWB) cite:alexander:1979timeless is to APL. cite:alexander:1977pattern


TWB starts with this:

#+begin_quote
/The Timeless Way of Building/ is the first in a series of books which
describe an entirely new attitude to architecture and planning.  The
books are intended to provide a complete working alternative to our
present ideas about architecture, building, and planning—an
alternative which will, we hope, gradually replace current ideas and
practices.

— A Timeless Way of Building
  cite:alexander:1979timeless
#+end_quote

Replace architecture and building with civilization and it's not a bad
description of W&W and APPL.

TWB was published two years after APL, which answers the chicken and
egg question, but it also makes sense.  TWB couldn't have been written
until after they had all but completed APL.

TWB is divided into three Parts: The Quality, The Gate, and The Way.

   Quality is QWAN.

   The Gate is the Patterns.

   The Way is how to get QWAN using the patterns.


The organization of the book also is design to work at multiple LODs,
like /The Plan of St. Gall/ with an outline of the entire work, and
then detailed TOCs at the beginning of each volume.



TWB is almost mystical -- it does not come across as a practical text
on how to build according to his philosophy and methodology.  It's
almost a manifesto.  This was on purpose, but as some reviews have
noted, it could be one reason that it hasn't been treated as seriously
as it should.  It's too outside of the mainstream, too easy to dismiss
and doesn't provide a bridge for architects and builders to cross from
their world into his.

The Oregon Experiment (which I still haven't seen) seems to be where
he shows a concrete example of how to plan, design, and build.

So what about W&W?  We don't need to cross any bridges that Alexandar
should have, but at the same time we need to bridge the gulf of how
civilization is today, how the present attempts at change are useless
and all but worthless.  So I suppose we do need bridges.  But is W&W
to be a bridge or manifesto?

I don't want to be too mystical, but I also don't want to be too
concrete which is why I'm so attracted to the Plan of St Gall (PSG).
St Gall was never built -- so the designs based on the plan are -- as
the title says -- paradigmatic. PSG delves deep providing historical,
social, economic and archaeological context and evidence.

So I suppose that W&W needs to blaze a path between the two -- so that
it's part Timeless Way and Part Plan of Arc Nong Pao.

In fact that's about right -- first volume should be closer to TWB and
the following volumes should provide three Plans -- two on earth and
one on mars.

In that respect I suppose we can borrow many things from Mollison's
Designer's Manual -- which is, in many respects, a path between TWB
and PSG.

The whole pace-layer model will take a bit to lay out -- and we will
have to make a case for why we are on the wrong path, and how we have
no choice but to start from first principles.

** Warp & Woof

The primer for the primer -- a kind of process philosophy where past
is part of the present -- and the future does no exist you can't go
into the future or back to the past because time is not linear -- we
are living in the Big Bang, we are part of the Big Bang, it didn't
create the universe, it's still going on, it IS the universe.

*** 

  - information
  - process
  - part-whole
  - pace-layers
  - systems & distributed systems
  - models & graphs
  - map-territory
  - quality
  - craftsmanship

*** The Plan of Arc Indradevi

A bioregion in n.e. cambodia

*** The Plan of Barsoon Dor

A river that runs from south to equater that is fed by ice from
antarctic to domes in warmer climes.


** APPL

structures used by the primer

** Primer

The origin story is the first part of the primer,[fn:1] followed by the
theses (declarations), then education (triv, quad, laurea etc), then
the shops and guilds, then the value-chain, then bioregions, and
finally production.

  - origin
  - theses
  - education
  - shops & guilds
  - value-chain
  - bioregions/ecosystems
  - production -- techne

** Hoard

After the primer is the Hoard -- the library of descriptive and
prescriptive knowledge.  This will be a map but a very detailed map
whose territory is the archive.

** Archive

After that is the Archive of all recorded memory and experience.



* Footnotes

[fn:1] What about language?  Origins lays out our history which is
tells what our metaphysics and physics.  The nuts and bolts of laguage
will be in the Triv.  but I'm talking about something deeper, more
structural -- language both spoken, written and executable -- a
language of the long now that will change far slower than language at
the upper pace layers -- it will change, but over centuries and
milennia not years and decades.  It should be something that is stable
for long periods of time.  Different pace-layers will have different
versions of it, the fashion layer tries out new ideas which are
filtered and refined until they change the lowest layers.


